arduino_1:
  baud: 115200 
  port: "/dev/ttyUSB2"

arduino_2:
  baud: 115200 
  port: "/dev/ttyUSB1"

pid_gains:
  - 10.0  # KP
  - 11.0  # KD
  - 12.0  # KI

motor_high_times:
  - 1400  # BLDC Motor Pairing PWM High Time (ms)
  - 1450  # BLDC Motor Dead Zone PWM High Time (ms)

servo_high_times:
  - 1000  # Servo Max Left PWM High Time (ms)
  - 1400  # Servo Centered PWM High Time (ms)
  - 1600  # Servo Max Right PWM High Time (ms)

servo_rads_range:
  - -1.5  # Servo Max Left Angle (rads)
  - 1.5   # Servo Max Right Angle (rads)

